apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: helloapi
    releaseName: product-helloapi
    version: "0.1.0"
    repo: ""
    chart: ../../chart
    valuesFile: ../../chart/values.yaml
    valuesInline:
      env: development
      message: "Hello from helloapi [DEV]"
      # replicaCount, service.*, resources.* → chart/values.yaml default'larından geliyor
