apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../

helmCharts:
  - name: chart
    releaseName: product-helloapi
    version: "0.1.0"
    valuesInline:
      env: development
      message: "Hello from helloapi [DEV]"
